local function doAndInsert(file, realname)
	MM[realname or file] = dofile("Functions/Scripts/"..file)
end

doAndInsert("isMM")
doAndInsert("init")
doAndInsert("Clues/InitPlayerClues", "InitPlayerClues")
doAndInsert("playerInit")
doAndInsert("assignRoles")
doAndInsert("canGameEnd")
doAndInsert("endGame")
doAndInsert("pingMurderers")
doAndInsert("playerWithGun")
doAndInsert("startVote")
doAndInsert("startTransition")
doAndInsert("startEndCamera")
doAndInsert("handleStorm")
doAndInsert("startShowdown")
doAndInsert("startOvertime")
doAndInsert("discordMessage")
doAndInsert("getpermlevel")
doAndInsert("pregame")
doAndInsert("countPlayers")
doAndInsert("NearbyLightning")
doAndInsert("GetPlayerRings")
doAndInsert("SetPlayerRings")
doAndInsert("RegisterEffect")
doAndInsert("ApplyPlayerEffect")
doAndInsert("scanMoneySectors")
doAndInsert("printMoney")
