name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Make build
      run: make

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: PTSR_GHBUILD
        path: build.pk3
